name: signal_fusion_default

# ---------------------------------------------------------------------------
# Assets — must match across all agents
# ---------------------------------------------------------------------------
assets:
  - BTC
  - ETH
  - SOL
  - BNB
  - XRP
  - ADA
  - AVAX
  - DOT
  - MATIC
  - LINK
  - UNI
  - ATOM
  - LTC
  - FIL
  - NEAR
  - APT
  - ARB
  - OP
  - INJ
  - SUI

# ---------------------------------------------------------------------------
# Agent names — must match agent_name used in storage
# ---------------------------------------------------------------------------
agent_names:
  whale: "whale_agent"
  narrative: "narrative_agent"
  technical: "technical_agent"
  market: "market_agent"
  derivatives: "derivatives_agent"

# ---------------------------------------------------------------------------
# Composite score weights (must sum to 1.0)
# ---------------------------------------------------------------------------
weights:
  whale: 0.30
  technical: 0.25
  derivatives: 0.20
  narrative: 0.15
  market: 0.10

# ---------------------------------------------------------------------------
# Score labels — evaluated top-down, first match wins
# ---------------------------------------------------------------------------
labels:
  - name: "STRONG BUY"
    min_score: 70
    direction: "buy"
  - name: "MODERATE BUY"
    min_score: 55
    direction: "buy"
  - name: "NEUTRAL"
    min_score: 45
    direction: "neutral"
  - name: "MODERATE SELL"
    min_score: 30
    direction: "sell"
  - name: "STRONG SELL"
    min_score: 0
    direction: "sell"

# ---------------------------------------------------------------------------
# Per-agent scoring rules
# Each agent maps its raw data to a 0-100 score per asset
# ---------------------------------------------------------------------------

scoring:
  # -----------------------------------------------------------------------
  # WHALE scoring (per asset)
  # -----------------------------------------------------------------------
  whale:
    # --- Ratio-based scoring (0-60 points) ---
    # Uses accumulate/(accumulate+sell) ratio instead of raw counts.
    # Scales correctly whether 10 or 300 transactions exist.
    # ratio = accumulate / (accumulate + sell)
    #   ratio 1.0 (100% accumulate)  → 60 points
    #   ratio 0.5 (balanced)          → 30 points
    #   ratio 0.0 (100% sell)         → 0 points
    scoring_mode: ratio              # "ratio" (new) or "per_move" (legacy)
    base_score: 50                   # base if no directional moves at all
    ratio_max_points: 60             # max points from accumulate/sell ratio
    ratio_center: 0.5               # ratio at which score = half of max
    min_directional_moves: 2         # need at least 2 acc+sell moves to use ratio

    # --- Exchange flow bonus/penalty (0-20 points) ---
    exchange_outflow_bonus: 10       # net outflow = accumulation across exchanges
    exchange_inflow_penalty: -10     # net inflow = selling across exchanges

    # --- Whale wallet signals (0-20 points) ---
    whale_wallet_accumulating_bonus: 8
    whale_wallet_reducing_penalty: -8

    # Clamp range
    min_score: 0
    max_score: 100

  # -----------------------------------------------------------------------
  # TECHNICAL scoring (per asset)
  # -----------------------------------------------------------------------
  # Rebalanced so neutral market ≈ 50, bearish indicators score > 0
  # Max bullish ≈ 85, max bearish ≈ 18, neutral midpoint ≈ 50
  technical:
    # RSI contribution (15-35 points)
    rsi:
      oversold_below: 30
      overbought_above: 70
      oversold_score: 35         # contrarian — good buying opportunity
      overbought_score: 15       # risky to enter
      neutral_min_score: 20      # RSI exactly at 30
      neutral_max_score: 35      # RSI exactly at 70

    # MACD contribution (5-15 points)
    macd:
      bullish_cross_points: 15   # MACD > signal line
      bearish_cross_points: 5    # MACD < signal line — was 0!

    # Moving average contribution (6-16 points)
    ma:
      above_ma7_points: 8        # price > 7-day MA
      above_ma30_points: 8       # price > 30-day MA
      below_ma7_points: 3        # price < 7-day MA — was 0!
      below_ma30_points: 3       # price < 30-day MA — was 0!

    # Trend confirmation (5-15 points)
    trend:
      bullish_points: 15         # trend classified as "bullish"
      bearish_points: 5          # trend classified as "bearish" — was 0!
      neutral_points: 10

  # -----------------------------------------------------------------------
  # DERIVATIVES scoring (per asset)
  # -----------------------------------------------------------------------
  # Rebalanced so neutral market ≈ 50, overcrowded/high-funding score > 0
  derivatives:
    # Long/short ratio contribution (15-35 points)
    long_short:
      sweet_spot_min: 0.55
      sweet_spot_max: 0.65
      sweet_spot_score: 35       # was 40 — healthy bullish
      overcrowded_above: 0.70
      overcrowded_score: 15      # was 10 — overcrowded longs still scores
      contrarian_below: 0.45
      contrarian_score: 30       # was 35 — heavy shorts contrarian
      default_score: 25          # unchanged

    # Funding rate contribution (10-30 points)
    funding:
      low_threshold: 0.0002
      low_score: 25              # was 30
      moderate_threshold: 0.0005
      moderate_score: 18         # was 15
      high_score: 10             # was 5 — high funding still scores
      negative_score: 30         # was 35

    # Open interest change contribution (0-30 points)
    open_interest:
      rising_score: 25           # OI increasing = conviction
      falling_score: 10          # OI decreasing = uncertainty
      stable_score: 15
      # Change threshold to classify rising/falling
      change_threshold_pct: 5    # >5% change from recent

  # -----------------------------------------------------------------------
  # NARRATIVE scoring (per asset) — 6-component scoring
  # -----------------------------------------------------------------------
  # Components (total max = 100):
  #   1. Volume (0-30):  normalised_score * volume_multiplier
  #   2. LLM sentiment (0-25):  from 12h LLM batch
  #   3. Community sentiment (0-15):  CryptoPanic votes
  #   4. Trending bonus (0-10):  CoinGecko trending
  #   5. Influencer bonus (0-10):  known influencers mentioning asset
  #   6. Multi-source bonus (0-10):  >= N sources have data
  # -----------------------------------------------------------------------
  narrative:
    # Component 1: Volume — normalised mentions vs rolling peak (0-30)
    volume_multiplier: 30

    # Component 2: LLM sentiment (0-25) — from 12h batch analysis
    llm_max_points: 25
    llm_min_confidence: 0.3          # ignore LLM results below this confidence

    # Component 3: Community sentiment (0-15) — CryptoPanic votes
    community_max_points: 15

    # Component 4: Trending bonus (0-10)
    trending_bonus: 10

    # Component 5: Influencer bonus (0-10)
    influencer_bonus: 10
    influencer_threshold: 2          # need >= N influencers mentioning asset

    # Component 6: Multi-source confirmation (0-10)
    multi_source_bonus: 10
    multi_source_threshold: 3        # need >= N sources with data

    # Cap
    max_score: 100

  # -----------------------------------------------------------------------
  # MARKET scoring (per asset)
  # -----------------------------------------------------------------------
  # Rebalanced: dampened contrarian F&G, bearish price still scores
  market:
    # Price change contribution (5-35 points)
    price_change:
      strong_positive_above: 5.0
      strong_positive_score: 35      # was 40
      positive_above: 0.0
      positive_score: 25             # was 30
      mild_negative_above: -5.0
      mild_negative_score: 15        # was 20
      strong_negative_score: 5       # was 10

    # Volume spike contribution (10-30 points)
    volume:
      spike_multiplier_above: 2.0
      spike_score: 30
      elevated_multiplier_above: 1.5
      elevated_score: 20
      normal_score: 10

    # Fear & Greed (global) (5-25 points)
    # Dampened contrarian — extreme fear is opportunity but not max score
    fear_greed:
      extreme_fear_below: 25
      extreme_fear_score: 25         # was 30 — dampened contrarian
      fear_below: 45
      fear_score: 20                 # was 25
      neutral_below: 55
      neutral_score: 15
      greed_below: 75
      greed_score: 10
      extreme_greed_score: 5

# ---------------------------------------------------------------------------
# Dynamic reweighting — adjust ALL agent weights based on data availability
# ---------------------------------------------------------------------------
# When any agent has missing/weak data for an asset, its weight is reduced
# and redistributed proportionally to agents with full data.
# This prevents fake-neutral scores (50.0) or zero scores (0.0)
# from dragging the composite toward the center or toward bearish.
#
# Tiers per agent:
#   full    — real, usable data → full weight
#   partial — some data but incomplete → half weight
#   none    — no useful data → zero weight, fully redistributed
#
# Detection is driven by the detail string and score from _score_dimension().
# Rules are YAML-configurable per agent below.
# ---------------------------------------------------------------------------
reweighting:
  enabled: true

  # Multiplier applied to each agent's weight based on its data tier
  tier_multipliers:
    full: 1.0          # full weight (e.g. 0.30 × 1.0 = 0.30)
    partial: 0.5       # half weight (e.g. 0.30 × 0.5 = 0.15)
    none: 0.0          # zero weight (redistributed to agents with data)

  # Per-agent tier detection rules
  agents:
    # WHALE: existing 3-tier system (accumulate/sell = full, transfers = partial, none = none)
    whale:
      no_data_keywords:
        - "no data"
        - "no whale activity"
        - "no scorer"
      full_data_keywords:
        - "accumulate"
        - "sell"
      # Everything else (e.g. "exchange outflow", "transfer") → partial

    # TECHNICAL: full when all indicators present, none when no data
    technical:
      no_data_keywords:
        - "no data"
      # No full_data_keywords → defaults to "full" when data exists

    # DERIVATIVES: none when no data, partial when only 1 of 3 metrics
    derivatives:
      no_data_keywords:
        - "no data"
        - "no deriv data"
      # When data exists, defaults to "full"

    # NARRATIVE: score-based detection — zero mentions = no data
    narrative:
      no_data_keywords:
        - "no data"
        - "low buzz"
      none_if_score_below: 1.0      # score 0 = genuinely no data
      partial_if_score_below: 15    # very weak narrative signal

    # MARKET: partial when only global F&G (not per-asset data)
    market:
      no_data_keywords:
        - "no market data"
      partial_keywords:
        - "F&G"                     # only global F&G, no per-asset data

# ---------------------------------------------------------------------------
# Conviction multiplier — amplify composite when dimensions agree
# ---------------------------------------------------------------------------
# When N+ dimensions independently agree on a direction, boost the composite
# score away from 50. This breaks the "everything is neutral" clustering
# problem and generates more actionable signals.
#
# Example: composite=56, 3 dimensions bullish → 56 + (56-50)*0.25 = 57.5
# Example: composite=42, 3 dimensions bearish → 42 - (50-42)*0.25 = 40.0
conviction:
  enabled: true
  min_agreeing_dimensions: 3    # need >= N dimensions scoring same direction
  boost_factor: 1.25            # multiply distance from 50 by this factor

# ---------------------------------------------------------------------------
# Momentum detection — compare current vs previous fusion run
# ---------------------------------------------------------------------------
momentum:
  # Minimum score change to flag as improving/degrading
  threshold: 5

  # Labels
  improving_label: "improving"
  degrading_label: "degrading"
  stable_label: "stable"

# ---------------------------------------------------------------------------
# Portfolio summary
# ---------------------------------------------------------------------------
portfolio:
  # How many top buys/sells to show
  top_n: 3

  # Minimum composite score to label as "high conviction"
  high_conviction_threshold: 70

  # Risk level rules (based on derivatives + market data)
  risk_levels:
    - name: "low"
      max_avg_funding: 0.0002
      min_fear_greed: 45
    - name: "elevated"
      max_avg_funding: 0.0005
      min_fear_greed: 20
    - name: "high"
      max_avg_funding: 1.0       # catch-all
      min_fear_greed: 0

  # Market regime from Fear & Greed
  regime_thresholds:
    extreme_fear: 25
    fear: 45
    neutral: 55
    greed: 75

# ---------------------------------------------------------------------------
# LLM insights (Claude Haiku)
# ---------------------------------------------------------------------------
llm_insights:
  enabled: true

  # Model to use
  model: "claude-haiku-4-5-20251001"

  # Max tokens per insight call
  max_tokens: 1024

  # System prompt for the LLM
  system_prompt: >
    You are a crypto market analyst. Given structured signal data, provide
    concise actionable insights. Focus on cross-dimensional patterns
    (e.g. whale accumulation during fear = opportunity). Compare with
    previous data when available to identify trend shifts. Be direct,
    no disclaimers. Max 3 sentences per asset, 5 sentences for portfolio.

  # What to include in LLM context
  include_previous_run: true

  # Generate per-asset insights
  per_asset: true

  # Generate portfolio-level summary
  portfolio_summary: true
